CREATE TABLESPACE tbs_task_site
  DATAFILE 'tbs_task_site.dat' 
    SIZE 10M
    REUSE
    AUTOEXTEND ON NEXT 10M MAXSIZE 200M;

CREATE TEMPORARY TABLESPACE tbs_temp_task_site
  TEMPFILE 'tbs_temp_task_site.dbf'
    SIZE 5M
    AUTOEXTEND ON;

CREATE USER TASK_SITE IDENTIFIED BY 1
DEFAULT TABLESPACE tbs_task_site
TEMPORARY TABLESPACE tbs_temp_task_site
QUOTA 20M on tbs_task_site;

GRANT CREATE SESSION TO TASK_SITE;
GRANT CREATE ANY TABLE TO TASK_SITE;
GRANT CREATE ANY INDEX TO TASK_SITE;
GRANT CREATE ANY SEQUENCE TO TASK_SITE;
GRANT CREATE ANY TRIGGER TO TASK_SITE;

